
services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app/graduation_projects_management
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true  # Allow interactive commands
    tty: true  # Keep the container running

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: graduation_projects
      MYSQL_USER: user
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
